// musicplayer-svelte/src/lib/Playlists.vue
<script setup>
import TablePage from "./TablePage.vue";
import { useMusicStore } from "../composables/useMusicStore.js";
//if going non-pinia route, store variables must be exposed in the setup function

const { playlists, getPlaylists } = useMusicStore();
getPlaylists();
const headers = [
	{ text: "Name", value: "name" },
	{ text: "Song Count", value: "songs" },
];
</script>

<template>
	<TablePage :items="playlists" :headers="headers">
		<template #h1>Playlists</template>
		<template #td_songs="{value}">{{value.length}}</template>
	</TablePage>
</template>

// musicplayer-react/src/components/Playlists.svelte
<script>
	import TablePage from "./TablePage.svelte";
	import SongCount from "./SongCount.svelte";
	import SongsLength from "./SongsLength.svelte";
	import { onDestroy } from "svelte";
	import { playlists, getPlaylists } from "../assets/musicStore.js";
	export let currentRoute;
	export let params;
	let playlistsList = [];
	const unsubscribe = playlists.subscribe((value) => (playlistsList = value));
	onDestroy(unsubscribe);
	getPlaylists();

	const headers = [
		{ text: "Name", value: "name" },
		{ text: "Songs", value: "songs", component: SongCount },
		{ text: "Length", value: "songs", component: SongsLength },
	];
</script>

<TablePage items={playlistsList} {headers}>
	<span slot="h1">Playlists</span>
</TablePage>
