// musicplayer-react/src/components/Albums.svelte
<script>
	import TablePage from "./TablePage.svelte";
	import SongCount from "./SongCount.svelte";
	import SongsLength from "./SongsLength.svelte";
	import { onDestroy } from "svelte";
	import { albums, getAlbums } from "../assets/musicStore.js";
	export let currentRoute;
	export let params;
	let albumsList = [];
	const unsubscribe = albums.subscribe((value) => (albumsList = value));
	onDestroy(unsubscribe);
	getAlbums();

	const headers = [
		{ text: "Name", value: "name" },
		{ text: "Artist", value: "artist" },
		{ text: "Songs", value: "songs", component: SongCount },
		{ text: "Length", value: "songs", component: SongsLength },
	];
	// test
	const getLength = (item) =>
		item.reduce((acc, value) => acc + value.length, 0);
</script>

<TablePage items={albumsList} {headers}>
	<span slot="h1">Albums</span>
</TablePage>

// musicplayer-svelte/src/lib/Albums.vue
<script setup>
import TablePage from "./TablePage.vue";
import { useMusicStore } from "../composables/useMusicStore.js";
//if going non-pinia route, store variables must be exposed in the setup function
const { albums, getAlbums } = useMusicStore();
getAlbums();
const headers = [
	{ text: "Name", value: "name" },
	{ text: "Artist", value: "artist" },
	{ text: "Songs", value: "songs" },
	{ text: "Length", value: "length" },
];
// test
const getLength = (item) => item.reduce((acc, value) => acc + value.length, 0);
</script>

<template>
	<TablePage :items="albums" :headers="headers">
		<template #h1>Albums</template>
		<template #td_songs="{ value }">{{ value.length }}</template>
		<template #td_length="{ item }">{{ getLength(item.songs) }}</template>
	</TablePage>
</template>
