// musicplayer-vue/src/components/TablePage.vue
<script setup>
import Page from "./Page.vue";

const props = defineProps({
	items: { type: Array, default: () => [] },
	headers: { type: Array, default: () => [] },
	rowValueKey: { type: String, default: "id" },
});
</script>

<template>
	<Page class="flex flex-col gap-8">
		<template #h1>
			<slot name="h1" />
		</template>
		<table class="w-full">
			<thead>
				<tr>
					<th
						v-for="(header, index) of headers"
						:key="header.text"
						class="text-left font-bold pr-2"
						:class="{
							'pr-2 pl-4': index === 0,
							'pr-4 pl-2': index === headers.length - 1,
							'px-2': index != 0 && index != headers.length - 1,
						}"
					>
						{{ header.text }}
					</th>
				</tr>
			</thead>
			<tbody>
				<tr
					v-for="item of items"
					:key="item[rowValueKey]"
					class="cursor-pointer rounded-md group/row"
				>
					<td
						v-for="(header, index) of headers"
						:key="header.text"
						class="text-left py-2 text-xl group-hover/row:bg-zinc-900"
						:class="{
							'pl-4 pr-2 rounded-l-full': index === 0,
							'pl-2 pr-4 rounded-r-full': index === headers.length - 1,
							'px-2': index != 0 && index != headers.length - 1,
						}"
					>
						<slot
							:name="`td_${header.value}`"
							:value="item[header.value]"
							:item="item"
						>
							{{ item[header.value] }}
						</slot>
					</td>
				</tr>
			</tbody>
		</table>
	</Page>
</template>

// musicplayer-svelte/src/lib/TablePage.svelte
<script>
	import Page from "./Page.svelte";

	export let items = [];
	export let headers = [];
	export let rowValueKey = "id";
</script>

<Page classname="flex flex-col gap-8">
	<slot slot="h1" name="h1" />
	<table class="w-full">
		<thead>
			<tr>
				{#each headers as header, index (index)}
					<th
						class={`text-left font-bold pr-2 ${
							(index === 0 && "pr-2 pl-4") ||
							(index === headers.length - 1 && "pr-4 pl-2") ||
							"px-2"
						}`}
					>
						{header.text}
					</th>
				{/each}
			</tr>
		</thead>
		<tbody>
			{#each items as item (item[rowValueKey])}
				<tr class="cursor-pointer rounded-md group/row">
					{#each headers as header, index (header.text)}
						<td
							class={`text-left py-2 text-xl group-hover/row:bg-zinc-900 ${
								(index === 0 && "pr-2 pl-4 rounded-l-full") ||
								(index === headers.length - 1 && "pr-4 pl-2 rounded-r-full") ||
								"px-2"
							}`}
						>
							{item[header.value]}
						</td>
					{/each}
				</tr>
			{/each}
		</tbody>
	</table>
</Page>
